server:
  port: 443
  ssl:
    enabled: true
    key-alias: "mimic-local-dev"
    key-store: "classpath:server-keystore.jks"
    key-store-password: "keystore"
    key-password: "keystore"
plain:
  server:
    port: 80