server:
  port: 443
  ssl: &serverssl
    enabled: true
    key-alias: "mimic-local-dev"
    key-store: "classpath:server-keystore.jks"
    key-store-password: "keystore"
    key-password: "keystore"
http:
  server:
    port: 80

# Spring config

spring:
  datasource:
    url: jdbc:h2:file:./db/h2-database
    username: test
    password: test
    driver-class-name: org.h2.Driver
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    maxActive: 50
    maxIdle: 5
    maxWait: 1000
    validationQuery: "select 1"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: MIMIC
liquibase:
  change-log: classpath:db/liquibase-changelog.xml

# Mimic-specific settings

mimic:
  scripts:
    dir: ./scripts

# Spring boot actuator configuration

management:
  port: 9000
  address: "127.0.0.1"
  ssl: *serverssl
  security:
    enabled: false

info:
  app:
    name: "Mimic"
    description: "Mimic Server"
    version: "1.0.0-SNAPSHOT"

endpoints:
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: false
  env.enabled: false
  mappings.enabled: false
  shutdown.enabled: false
  trace.enabled: false
  loggers.enabled: false
  auditevents.enabled: false
  heapdump.enabled: false
  error.enabled: false

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN
#  org.springframework.boot.autoconfigure: DEBUG