server:
  port: 443
  ssl: &serverssl
    enabled: true
    key-alias: "mimic-local-dev"
    key-store: "classpath:server-keystore.jks"
    key-store-password: "keystore"
    key-password: "keystore"
http:
  server:
    port: 80

# Mimic-specific settings

mimic:
  scripts:
    dir: ./scripts

# Spring boot actuator configuration

management:
  port: 9000
  address: "127.0.0.1"
  ssl: *serverssl
  security:
    enabled: false

info:
  app:
    name: "Mimic"
    description: "Mimic Server"
    version: "1.0.0-SNAPSHOT"

endpoints:
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: false
  env.enabled: false
  mappings.enabled: false
  shutdown.enabled: false
  trace.enabled: false
  loggers.enabled: false
  auditevents.enabled: false
  heapdump.enabled: false
  error.enabled: false
