server:
  port: 443
  ssl: &serverssl
    enabled: true
    protocol: TLSv1.2
    enabled-protocols: TLSv1.1+TLSv1.2
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
    key-alias: "mimic-local-dev"
    key-store: "classpath:server-keystore.jks"
    key-store-password: "keystore"
    key-password: "keystore"
http:
  server:
    port: 80

# Spring config

spring:
  datasource:
    url: jdbc:h2:file:./db/h2-database
    username: test
    password: test
    driver-class-name: org.h2.Driver
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    maxActive: 50
    maxIdle: 5
    maxWait: 1000
    validationQuery: "select 1"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: MIMIC
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

# Mimic-specific settings

mimic:
  scripts:
    dir: ./scripts

# Spring boot actuator configuration

management.server:
  port: 9000
  address: "127.0.0.1"
  ssl: *serverssl
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics

info:
  app:
    name: "Mimic"
    description: "Mimic Server"
    version: "1.0.0-SNAPSHOT"

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN
#  org.springframework.boot.autoconfigure: DEBUG